name: oeis
channels:
  - conda-forge
dependencies:
  - python
  - ipython
  - pytest
  - pytest-cov
  - hypothesis
  - coverage
  - coveralls
  - pylint
  - black
  - numpy
  - sympy
  - wrapt
  - python-box
  - requests
  - aiohttp
  - pip
  - pip:
    - bandit
