name: oeis
channels:
  - conda-forge
dependencies:
  - ipython
  - pytest
  - pytest-cov
  - codecov
  - coverage
  - pylint
  - black
  - numpy
  - sympy
  - wrapt
  - requests
  - aiohttp
  - python-box
  - pip:
    - bandit
